// Slender Pins — factoid bank
// Behavioural science, psychology, and distilled philosophical / religious wisdom.
// Tuned for a band working toward an EP: motivation, groups, deadlines, craft, meaning.
// Edit freely — keep the array structure.

const FACTS = [
  // ============ GROUP DYNAMICS & MOTIVATION ============
  "The Köhler effect, identified by Otto Köhler in 1926 studying Berlin rowing clubs, shows that the weaker members of a group work harder when their effort is visible and genuinely matters to the shared result — the opposite of slacking off.",
  "Social loafing — people pulling less weight in a group than alone — was first measured by Max Ringelmann in the 1910s, pulling on ropes. Eight people pulled less than eight times one person. Effort dilutes when no one's individual contribution is seen.",
  "The Zeigarnik effect: unfinished tasks occupy the mind more than finished ones. Bluma Zeigarnik noticed waiters could recall unpaid orders perfectly, then forgot them the instant the bill was settled. Starting a thing makes it nag at you to finish.",
  "Parkinson's Law: work expands to fill the time available for its completion. Give yourselves a month for a mix and it takes a month; give yourselves a weekend and somehow it gets done. Cyril Northcote Parkinson, 1955.",
  "The planning fallacy, named by Kahneman and Tversky, is the near-universal tendency to underestimate how long your own projects will take — even when you know similar projects always overran. Every band thinks the EP is nearly done.",
  "The IKEA effect: people value things more when they helped build them. Researchers found subjects would pay more for furniture they'd assembled themselves, however wonky. Effort poured into a thing becomes attachment to it.",
  "The goal-gradient effect: motivation increases as you near the finish. Rats run faster near the end of a maze; people with a 10-stamp coffee card buy faster once they have a few stamps. The closer the EP gets, the easier the last push feels.",
  "Brainstorming in a group often produces fewer and worse ideas than the same people thinking alone first, then pooling. The effect is called 'production blocking' — waiting your turn to speak quietly kills the idea you were holding.",
  "Deadlines work, but specific ones work far better. Studies on 'implementation intentions' show that 'I'll track vocals Tuesday at 7pm at Dan's' is dramatically more likely to happen than 'I'll track vocals soon'.",
  "The mere presence of others changes performance — the 'audience effect'. Simple, well-learned tasks improve when watched; hard, unfamiliar ones get worse. You'll nail the part you know cold and fumble the new one when someone's listening.",
  "Teams with a shared, specific deadline coordinate better than teams told only to 'finish when ready'. Ambiguity about the endpoint is one of the most reliable ways a group project stalls indefinitely.",
  "The 'sucker effect' is why people stop contributing: if someone believes others are loafing, they cut their own effort to avoid being the only one carrying the weight. Visible fairness keeps a group pulling together.",
  "Small wins compound. Teresa Amabile's research on creative work found that the single biggest day-to-day motivator isn't praise or money — it's the feeling of making progress, however small. Tick one thing off and the next gets easier.",
  "Public commitment raises follow-through. People who state a goal to others are measurably more likely to act on it than those who keep it private — the social cost of backing out does the work.",
  "Deadlines you set for yourself are routinely missed; deadlines imposed from outside are routinely met. Dan Ariely found students given evenly-spaced external deadlines outperformed those allowed to set their own.",

  // ============ DECISION-MAKING & COGNITION ============
  "The endowment effect: once you own something, you value it more highly than before you owned it. A mix you've lived with for weeks feels better than it is, simply because it's yours. Fresh ears exist for a reason.",
  "Decision fatigue is real: the more choices you make in a day, the worse your later choices get. Judges grant parole far more often early in the day than just before lunch. Make the big creative calls when you're fresh.",
  "The sunk cost fallacy: people keep pouring effort into something because of what they've already spent, not because it's worth finishing. Sometimes the bravest mix decision is to scrap the take you spent all night on.",
  "Loss aversion: losses feel about twice as powerful as equivalent gains. Kahneman and Tversky showed the pain of losing £50 outweighs the pleasure of winning £50. We protect what we have more fiercely than we chase what we don't.",
  "The availability heuristic: we judge how likely something is by how easily examples come to mind. Vivid, recent, or emotional events feel more probable than they are. The one disastrous gig looms larger than ten good ones.",
  "Anchoring: the first number mentioned warps every estimate that follows, even when it's arbitrary. Negotiators exploit it; so does any quote you're given. Whoever says a figure first sets the gravity for the whole conversation.",
  "Confirmation bias: we seek and remember evidence that supports what we already believe, and overlook what doesn't. The cure isn't trying harder to be fair — it's actively hunting for the case against yourself.",
  "The Dunning-Kruger effect: the less skilled you are at something, the less able you are to see how unskilled you are — because the same knowledge needed to do it well is what's needed to judge it. Competence includes knowing what you don't know.",
  "Hyperbolic discounting: we massively overvalue rewards now versus later. £10 today can feel better than £15 next month. It's why finishing later always loses to scrolling now — the future reward is real but feels faint.",
  "Choice overload: more options can reduce satisfaction and stall decisions entirely. Faced with 24 jams, shoppers bought less than when faced with 6. Too many plugin options can be as paralysing as too few.",
  "The framing effect: the same fact stated as a gain or a loss changes the decision. '90% of mixes survive this move' lands differently from '1 in 10 mixes are ruined by it'. Identical odds, opposite feelings.",
  "Cognitive load: the working mind holds only a few things at once — famously 'about seven', though later work says closer to four. Overload it and everything degrades. Write the idea down and free the slot.",
  "The peak-end rule: we judge an experience by its most intense moment and its ending, not its average. A song with a stunning bridge and a strong finish is remembered as great, even if the verses sag.",
  "Status quo bias: we prefer things to stay as they are, treating the current state as a safe default even when change would help. The arrangement you've had for months feels 'right' partly just because it's there.",

  // ============ HABITS, FOCUS, PROCRASTINATION ============
  "Habits form through cue, routine, reward — not willpower. The reliable way to build one isn't motivation but attaching the new behaviour to an existing trigger: 'after I make coffee, I open the session'.",
  "Procrastination is an emotion-regulation problem, not a time-management one. We put off tasks that make us feel anxious or inadequate. The task isn't the enemy; the feeling it stirs is. Naming that often dissolves the stall.",
  "The two-minute rule: if something takes under two minutes, do it now. Small undone tasks accumulate into a fog of low-grade dread far heavier than the tasks themselves.",
  "Attention residue: when you switch tasks, part of your mind stays stuck on the last one. Sophie Leroy's research shows multitasking leaves a 'residue' that degrades focus. Finish, or deliberately park, before moving on.",
  "It takes on average 23 minutes to fully refocus after an interruption, by Gloria Mark's research. Every 'quick check' of the phone mid-session costs far more than the check itself.",
  "Temptation bundling: pair something you should do with something you want. Only listen to that podcast while doing the boring admin. Katherine Milkman found it measurably increases follow-through.",
  "The fresh start effect: people are more likely to pursue goals right after a temporal landmark — a Monday, a birthday, the first of the month. New beginnings feel like clean slates, and that feeling is usable fuel.",
  "Willpower behaves partly like a muscle that tires with use, and partly like a belief — those who think it's unlimited show less depletion. How you frame your own stamina shapes how much you have.",
  "Deep work — long, unbroken, undistracted focus — is increasingly rare and increasingly valuable precisely because everything is built to interrupt it. The ability to concentrate hard for two hours is now almost a superpower.",
  "Implementation intentions ('if X, then Y') roughly double the odds of acting on a goal. Deciding the when, where, and how in advance removes the in-the-moment negotiation where good intentions usually die.",
  "Precommitment beats willpower. Odysseus had himself tied to the mast rather than trust his future self near the Sirens. Deleting the app, leaving the phone in another room — same principle, less rope.",

  // ============ MEMORY & LEARNING ============
  "The spacing effect: information reviewed across spread-out sessions sticks far better than the same time crammed at once. Learning a part over five short days beats one long night, every time.",
  "The testing effect: trying to recall something strengthens memory more than re-reading it. Struggling to remember the chord change burns it in deeper than looking it up again.",
  "The disfluency effect: material that's slightly harder to process — an awkward font, a tricky exercise — can be remembered better, because the difficulty forces deeper engagement. Easy isn't always how things stick.",
  "Robert Bjork's 'desirable difficulties': the conditions that make learning feel harder and slower often make it stronger and more lasting. The smooth, easy practice that feels productive frequently isn't.",
  "Sleep consolidates memory and learning. Musicians often play a passage better the morning after practising than they did that night — the brain rehearses and files it during sleep. Sometimes the best practice is to stop and sleep.",
  "Chunking: experts don't have better memories, they have better groupings. A chess master sees a board as a few meaningful patterns, not 32 pieces. You learn a song faster as four sections than as two hundred bars.",
  "Interleaving — mixing different skills in one practice session rather than blocking them — feels messier but produces better retention and transfer than drilling one thing at a time.",
  "Memory is reconstructive, not a recording. Each recall subtly rewrites the memory. Eyewitnesses, and bandmates arguing about 'what we agreed last week', are both genuinely, confidently wrong all the time.",

  // ============ CREATIVITY & CRAFT ============
  "Constraints boost creativity. Total freedom often paralyses; a tight limit — three chords, one mic, sixty seconds — forces invention. The blank page is the enemy, not the small box.",
  "The incubation effect: stepping away from a problem lets the unconscious keep working, and solutions often arrive in the shower or on a walk. Banging at it without breaks is frequently the slowest route.",
  "Quantity breeds quality. In a famous ceramics-class study, the group graded on volume of pots made produced better pots than the group graded on a single perfect one — because they learned by doing, not agonising.",
  "Brian Eno's Oblique Strategies are a deck of cards offering lateral prompts ('honour thy error as a hidden intention') to break creative deadlock. Built in 1975, used on Bowie, U2, Coldplay. Friction, deliberately introduced.",
  "The 'beginner's mind' (shoshin) in Zen: the expert sees few possibilities, the beginner sees many. Mastery can narrow vision. Approaching a familiar instrument as if for the first time can reopen it.",
  "Creativity is often recombination, not invention from nothing. Most original ideas are unexpected connections between existing things. Steal broadly, combine strangely — that's most of how new music gets made.",
  "Deliberate practice — focused, effortful work on the specific things you can't yet do, with feedback — is what separates improvement from mere repetition. Playing the easy bits again isn't practice; it's hiding.",
  "The 'first idea' is rarely the best, but it clears the channel. Studios call it 'getting the bad take out'. You often have to play the obvious thing before the interesting thing will come.",

  // ============ PHILOSOPHICAL WISDOM ============
  "Dostoevsky's 'Grand Inquisitor' parable in The Brothers Karamazov argues that people will trade freedom for security, bread, and certainty — that most don't actually want the burden of free choice a meaningful life demands.",
  "Camus took the myth of Sisyphus — condemned to roll a boulder uphill forever — and argued we must imagine him happy: meaning isn't found in finishing, but in the wholehearted doing of the task itself.",
  "Nietzsche's 'eternal recurrence' is a test: if you had to live this exact life, every detail, infinitely, would you embrace it? It's not a cosmology but a question — are you living a life you'd choose again?",
  "The Stoics distinguished what's 'up to us' (our judgements, choices, effort) from what isn't (outcomes, others, fortune). Epictetus said peace comes from caring intensely about the first and letting go of the second.",
  "Socrates claimed his only wisdom was knowing that he knew nothing. The 'Socratic paradox' — that admitting ignorance is the start of understanding — undercuts every confident expert, gently.",
  "Kierkegaard saw anxiety as 'the dizziness of freedom' — the vertigo you feel standing before genuine choice, aware you could do anything. Not a malfunction but the felt weight of being free.",
  "Aristotle located virtue in the mean between extremes: courage between cowardice and recklessness, generosity between stinginess and waste. The good life is a matter of proportion, found by practice, not formula.",
  "Sartre: 'existence precedes essence'. There's no fixed human nature handed down; you are what you do. You're not a guitarist who happens to act — you're the sum of your choices, made and remade.",
  "Hume's guillotine: you can't derive an 'ought' from an 'is'. No pile of facts about the world, by itself, tells you what you should do. Values are something we bring, not something we find lying around.",
  "Wittgenstein ended his first great work by saying the most important things can't be spoken, only shown: 'whereof one cannot speak, thereof one must be silent.' Some truths are gestured at, not stated — which is most of why music exists.",
  "The 'veil of ignorance', from John Rawls: design society's rules as if you didn't know who you'd be born as. A test for fairness — would you accept this arrangement from any position in it?",
  "Pascal's Wager frames belief as a bet under uncertainty, weighing infinite possible gain against finite cost. Whatever you think of the theology, it's an early, sharp piece of decision theory under radical uncertainty.",
  "Diogenes the Cynic performed his philosophy: living in a jar, owning nothing, mocking pretension, asking only that Alexander the Great step out of his sunlight. A life arguing that almost everything we chase is unnecessary.",
  "Heraclitus: you cannot step in the same river twice, for it is not the same river and you are not the same person. Everything flows. The band you were last year and the one recording now are not quite the same band.",
  "The Buddhist concept of anicca — impermanence — holds that clinging to things as if they were permanent is the root of suffering, because nothing is. The mix will never be 'done' and finished forever; release it and let it go.",
  "Marcus Aurelius wrote his Meditations only to himself, never for publication — a Roman emperor's private notes on staying humble, doing his duty, and remembering he would die. The most powerful man alive, talking himself down to size.",
  "Plato's allegory of the cave: prisoners mistake shadows on a wall for reality, and the one who escapes to the light is blinded, then disbelieved on return. Seeing truly is disorienting, and unpopular.",
  "Simone de Beauvoir argued that freedom is only meaningful in relation to others' freedom — that an ethics worth having binds your liberation to everyone else's. You are not free alone.",
  "The Ship of Theseus: if every plank of a ship is replaced over time, is it the same ship? Asked since antiquity. Applies to your body's cells, your band's line-up, and the song that's been rearranged past recognition.",
  "Epicurus argued we shouldn't fear death: 'where death is, we are not; where we are, death is not.' We never actually experience our own non-existence, so the dread is of something we'll never meet.",

  // ============ RELIGIOUS & SPIRITUAL WISDOM ============
  "The Tao Te Ching prizes wu wei — 'effortless action', moving with the grain of things rather than forcing them. Water wears down rock not by struggling but by yielding and persisting. Some parts are played, not forced.",
  "The Hebrew concept of the Sabbath built rest into the structure of the week as sacred, not optional — a radical idea in the ancient world: that stopping work is itself holy, and that you are more than your labour.",
  "The Buddhist parable of the second arrow: when life strikes you (the first arrow), the suffering you add through resentment and rumination is the second arrow — and that one is optional. Pain is given; suffering is partly chosen.",
  "Ecclesiastes, one of the strangest books in the Bible, concludes that much is 'vanity' — vapour, breath, fleeting — and that the wise response is to eat, work, and find satisfaction in the doing, since the rest is beyond us.",
  "The Sufi poet Rumi: 'the wound is the place where the light enters you.' Damage and breaking are framed not as the end of meaning but as the opening through which it arrives.",
  "The Zen koan is a question with no logical answer ('what is the sound of one hand clapping?') designed to exhaust rational thinking until insight breaks through sideways. Understanding that can't be reasoned to.",
  "The Bhagavad Gita's central teaching: act without attachment to the fruits of action. Do the work fully, but release your grip on the outcome — a 2,000-year-old answer to performance anxiety.",
  "The Christian concept of kenosis — self-emptying — describes love as pouring yourself out rather than filling yourself up. A counter-model to a culture of accumulation and self-promotion.",
  "In many mystical traditions — Christian, Sufi, Hindu — the deepest knowing is 'apophatic': you can only say what the divine is not, never what it is. Truth approached by subtraction, like carving away everything false.",
  "The Jewish principle of tikkun olam — 'repair of the world' — frames human work as the ongoing mending of a broken creation. Meaning located not in escaping the world but in fixing your corner of it.",
  "The Desert Fathers, early Christian hermits, sought God through radical simplicity and silence in the Egyptian desert. One was asked what he did all day. He said: 'I fall down, and I get up. I fall down, and I get up.'",
  "Karma, in its original Hindu and Buddhist sense, isn't cosmic punishment but causation: actions ripple outward and shape what comes. Less 'you'll be punished' and more 'everything you do becomes part of the chain'.",
  "The Quran describes the human being as carrying a 'trust' that the mountains and heavens declined to bear — the weight of moral responsibility and free choice. Freedom as a burden too heavy for the earth itself.",
  "Meister Eckhart, the medieval mystic, said: 'if the only prayer you ever say is thank you, that will be enough.' Gratitude framed as the whole of spiritual practice, distilled.",
  "The Stoic and Christian traditions both prize 'memento mori' — remember you will die — not as morbidity but as clarity. Knowing the set is finite changes how you play every song in it.",

  // ============ EMOTION, RELATIONSHIPS, SELF ============
  "The 'spotlight effect': we wildly overestimate how much others notice us. Most people are far too busy worrying about their own performance to clock your bum note. The audience is its own anxious spotlight.",
  "Emotional contagion is real: moods spread through groups, often unconsciously, within minutes. One person's tension or ease ripples through a rehearsal room. Who you bring to a session changes the session.",
  "The Gottman ratio: stable relationships maintain roughly five positive interactions for every negative one. Applies to bands too — a group that only ever critiques, never appreciates, quietly corrodes.",
  "Naming an emotion reduces its intensity — 'affect labelling', shown in brain scans to calm the amygdala. Saying 'I'm frustrated with this take' literally takes some of the heat out of it.",
  "The negativity bias: bad is stronger than good. One harsh comment outweighs several kind ones; criticism sticks while praise slides off. Knowing this, weight your feedback accordingly.",
  "Psychological safety — the shared belief that you won't be humiliated for speaking up — was Google's single biggest predictor of effective teams. The band where it's safe to suggest a bad idea makes more good ones.",
  "Self-compassion outperforms self-criticism for actual improvement. Kristin Neff's research shows being kind to yourself after a mistake leads to more learning and persistence than beating yourself up.",
  "The 'misattribution of arousal': we often mislabel the cause of our physical states. Adrenaline before a gig can be read as fear or as excitement — and the reading changes the experience. Same racing heart, different story.",
  "Flow — total absorption in a task — happens at the edge between boredom and anxiety, where challenge just exceeds current skill. Too easy and you drift; too hard and you panic. The sweet spot is learnable.",
  "Venting anger doesn't reduce it — it rehearses it. The catharsis theory is largely a myth; hitting a pillow makes you more aggressive, not less. Sitting with the feeling works better than acting it out.",

  // ============ ECONOMICS & GAME THEORY ============
  "The prisoner's dilemma shows why rational individuals often fail to cooperate even when both would benefit. Trust is the thing that solves it — and trust is built by repetition, by playing the game together many times.",
  "The tragedy of the commons: shared resources get overused because each person's incentive is to take a bit more, until there's nothing left. Applies to anything held in common — including a band's collective patience.",
  "Loss-framed effort: people work harder to avoid losing something they've been given than to gain the same thing. Some studios pay bonuses upfront and claw them back on missed deadlines — it works better than promising them later.",
  "Opportunity cost: the true cost of anything is what you give up to have it. Every hour on the perfect kick drum is an hour not spent writing the next song. What isn't the time being spent on?",
  "Diminishing returns: each extra unit of effort yields less than the last. The first hour of mixing transforms the track; the tenth moves a fader 0.5dB no one will hear. Knowing when to stop is a skill.",
  "Goodhart's Law: when a measure becomes a target, it stops being a good measure. Chase streaming numbers and you may optimise away the thing that made the music worth streaming.",
  "Network effects: some things get more valuable the more people use them. A scene, a sound, a shared reference — value that compounds with adoption. Why being early to a movement matters.",

  // ============ MISC. SHARP IDEAS ============
  "Survivorship bias: we study the winners and miss the lessons of the failures we never see. Every 'how we made it' story omits the thousand identical bands that did the same things and vanished.",
  "Chesterton's Fence: don't remove a rule or structure until you understand why it was put there. Before you scrap the band's old way of doing things, find out what problem it was quietly solving.",
  "Hanlon's Razor: never attribute to malice what is adequately explained by carelessness or a missed text. Most band conflicts are logistics and tiredness, not betrayal.",
  "Occam's Razor: the simplest explanation that fits is usually the best. The simplest arrangement that serves the song is usually the best too. Strip before you add.",
  "The Pareto principle: roughly 80% of effects come from 20% of causes. A small fraction of your effort produces most of the result. Find the 20% of the song that's doing the work and protect it.",
  "The map is not the territory (Korzybski): your model of a thing is never the thing itself. The demo is not the song; the plan is not the EP. Don't mistake the representation for the reality.",
  "The Dunbar number: humans can maintain only around 150 stable relationships, a limit set by brain size. Scenes, like villages, hold together up to a point and then fragment. There's a reason tight crews stay small.",
  "Loss of a streak hurts more than never starting one — which is exactly why streaks (of practice, of writing, of showing up) are such powerful motivators. Don't break the chain.",
  "The bystander effect: the more people present, the less likely any one of them acts, because responsibility diffuses. In a band, 'someone should book the studio' often means no one does. Name who.",
  "Cunningham's Law: the best way to get the right answer online isn't to ask a question — it's to post the wrong answer and wait for corrections. People would rather fix than help. Useful, and a little bleak.",
  "Hofstadter's Law: it always takes longer than you expect, even when you take Hofstadter's Law into account. The most honest thing ever said about finishing a creative project.",
  "The 'curse of knowledge': once you know something, you can't imagine not knowing it, which makes experts bad at explaining and bad at hearing their own work freshly. You can no longer hear your song the way a stranger will.",
  "Brandolini's Law: the energy needed to refute nonsense is an order of magnitude greater than the energy needed to produce it. Why bad takes are quick and good arguments are slow.",
  "The Lindy effect: for non-perishable things like ideas and songs, the longer they've already survived, the longer they're likely to last. A melody that's stuck around a year may outlast one that's hot this week.",
  "Loss of context kills good ideas: a brilliant fragment recorded with no note about what it was for is often unusable later. Capture the idea AND why it mattered. Future-you is a stranger.",
  "Default bias: whatever is set as the default is what most people end up with, because changing it takes effort. Set your session, your tuning, your workflow defaults deliberately — they'll quietly decide most of your choices.",
  "The 'fundamental attribution error': we explain others' behaviour by their character and our own by circumstance. They were late because they're flaky; you were late because traffic. Almost everyone does this almost always.",
  "Loss framing in practice: 'we have three weekends left before the EP deadline' motivates more than 'we have three weekends to work on the EP'. Scarcity of time, made visible, focuses a group fast.",
  "The Einstellung effect: knowing one solution can blind you to a better one. Experienced players often miss the simpler part because they reach for the familiar pattern first. Sometimes expertise is the obstacle.",
  "The 'less-is-better effect': in isolation, people sometimes value a smaller, complete thing over a larger, flawed one. A tight three-track EP can land harder than a sprawling, uneven album. Finish small over sprawling unfinished.",
  "Decision paralysis often dissolves the moment you make any choice reversible. 'We'll try it this way and can always change it' unsticks a group far faster than treating every call as permanent.",
  "Loss of momentum is the real project killer, not loss of talent. Amabile's diary studies found that the catastrophic days for creative work were the ones with setbacks and stalls — small, repeated progress is what sustains a project to the end."
];

// Expose for the strip
window.FACTS = FACTS;
